import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  nav,
}: Readonly<{
  children: React.ReactNode;
  nav: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-row`}>
        <nav className="flex flex-col w-[256px] border-r-2 border-black h-dvh p-2">
          {nav}
        </nav>
        <main className="p-2">{children}</main>
      </body>
    </html>
  );
}
